server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: vhost
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/cdok
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui